# BEGIN_KITTY_THEME
# kanagawabones

font_family    JetBrainsMono Nerd Font 
map f1 launch --cwd=current
# END_KITTY_THEM


# BEGIN_KITTY_THEME
# Kanagawa
include current-theme.conf
# END_KITTY_THEME
